### ISSUE TITLE
setting “python_requires” with ">3,!=3.10" is a better way to declare Python compatibility

### ISSUE THREAD

**Issue by PyVCEchecker** [jazzband/django-categories#176]
Hello!
I noticed that django-categories  "Removed support for Python 2.7" and "incompatible with Python 3.10".
I guess you want to limit compatible python versions. And I think it is a better way to declare Python compatibility by using the keyword argument **python_requires** for some reasons:
* Descriptions in **python_requires** will be reflected in the metadata
* “pip install” can check such metadata on the fly during distribution selection , and prevent from downloading and installing the incompatible package versions. 
* If the user does not specify any version constraint, pip can automatically choose the latest compatible package version for users.

Way to improve:
modify **[options]** in **setup.cfg** add **python_requires** keyword argument:
```python
[options]
python_requires = >3,!=3.10
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by PetrDlouhy** [comment]
Not sure where the incompatibility with Python 3.10 is declared, but it does pass all tests in 3.10.
Is it resolved or is the case uncovered by tests?

**Comment by PetrDlouhy** [comment]
@PyVCEchecker I don't see any incompatibility with Python 3.10. If there is any incompatibility, please reopen this issue.
