### ISSUE TITLE
New release 1.9.3

### ISSUE THREAD

**Issue by PetrDlouhy** [jazzband/django-categories#187]
Hi @coordt, @epicserve, @jezdez, others,

since this project moved to Jazzband I tried to clean it up a bit. I have fixed the testing, updated the matrix, tried to fix the docs (but I don't have rights to the original RtD repo), removed some obsolete code and pulled those PRs that are (hopefully) non-controversial.

I would like to make a new release, but I am not sure if I have permissions for it and also I would like somebody to check the changes.
Do you think you can look at that?

**Comment by epicserve** [comment]
I looked and I don't have access to RtD account either.

**Comment by epicserve** [comment]
@PetrDlouhy, not idea. I haven't touched it since it has moved to Jazzband.

**Comment by coordt** [comment]
@PetrDlouhy What permissions do you need. I don't think I have any/many, but I can look.

**Comment by PetrDlouhy** [comment]
@coordt To release on PyPI (https://pypi.org/project/django-categories/). My username is `petr.dlouhy`, but since the project moved to Jazzband I am not sure what the process should be.

**Comment by coordt** [comment]
An invite was sent your way from PyPI.

**Comment by PetrDlouhy** [comment]
@coordt Thank you very much. The 1.9.3 is released now.
