### ISSUE TITLE
Can't install alongside Django 1.5b2

### ISSUE THREAD

**Issue by maiksprenger** [jazzband/django-categories#59]
I'm developing against Django 1.5 beta, and always got an error when installing. After a bit of fiddling, I know that installing django-categories in a clean (--no-site-packages) virtualenv

a) together with Django 1.4.3 works fine (pip install Django django-categories)
b) after having installed Django 1.4.3 works fine (pip install Django && pip install django-categories)
c) together with Django 1.5b2 works fine (surprisingly!) (pip install https://www.djangoproject.com/download/1.5b2/tarball/ django-categories)
d) after having installed Django 1.5b2 fails (pip install https://www.djangoproject.com/download/1.5b2/tarball/ && pip install django-categories)

The log is here: https://gist.github.com/560478e396afa1a289b1

I presume the error has to do with trying to import django.db.models.Q without having settings setup.

**Comment by PetrDlouhy** [comment]
This issue seems to refer to very old version of Django/django-categories. I am closing it. Please reopen if it is still relevant to the currently supported version of Django or newest version `2.0.0` of `django-categories`.

**Comment by maiksprenger** [comment]
Haha, it's 12 years old, couldn't agree more! Thanks Petr!
