### ISSUE TITLE
Django 1.5 and adminmedia

### ISSUE THREAD

**Issue by maiksprenger** [jazzband/django-categories#60]
The TreeEditor is currently not functional in Django 1.5 because it's templates use the removed adminmedia tag library. This bug report says it all: https://github.com/feincms/feincms/issues/371

As per: https://docs.djangoproject.com/en/dev/releases/1.5-beta-1/

```
The template tags library adminmedia, which only contained the deprecated
template tag {% admin_media_prefix %}, was removed. Attempting to load
it with {% load adminmedia %} will fail. If your templates still contain
that line you must remove it.
```

**Comment by PetrDlouhy** [comment]
This issue seems to refer to very old version of Django/django-categories. I am closing it. Please reopen if it is still relevant to the currently supported version of Django or newest version `2.0.0` of `django-categories`.
